# name of compiled binary (without .in/.hex extension)
# default is "main"
TARGET = rx_demo

# Your source files
SRCS = rx_demo.c
SRCS += 

# ---------These paths and dirs are relative to this makefile's path----------
# Yor source (.c/.s) file's location
SRC_DIR = src
# Location of compiled binary
BUILD_DIR = build
# Location of the library
LIBRARY_PATH = ../../lib


# include the main Makefile
include ../Makefile.include
